services:
  php:
    build:
      context: .
    container_name: smilehub_php_container
    ports:
      - "8080:80"                  # Rest API port link
    volumes:
      - ./:/var/www/html
      - ./apache.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: smilehub_mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: smilehub_db   # Database name
      MYSQL_USER: root              # DB username
      MYSQL_PASSWORD:               # Set to an empty string
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: smilehub_phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootsecret
    ports:
      - "8081:80"                   # PHPMyAdmin port link
    depends_on:
      - mysql      

volumes:
  mysql_data: